on: push
name: Prettier
jobs:
  lint:
    name: prettier-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Lint
        uses: CultureHQ/actions-yarn@master
        with:
          args: test
